### ISSUE TITLE
mail.ru emails are all invalid

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/check-if-email-exists#771]
From a user.

To be confirmed.

**Comment by tyranron** [comment]
@amaurymartiny checked this

```
/ # telnet mxs.mail.ru 25
Connected to mxs.mail.ru
220 mxs.mail.ru ESMTP ready 
HELO mail.example.com  
250 mxs.mail.ru
MAIL FROM: <robot@example.com>
250 2.0.0 OK
RCPT TO: <ya.jeam@mail.ru>
250 Go ahead
```

So, again this [doesn't fit the deliverability check](https://github.com/amaurymartiny/check-if-email-exists/blob/v0.8.17/core/src/smtp/mod.rs#L204-L210). I guess this situation will happen again and again in future, due to the messages not being standardized. 

The problem with this issue that it's too subtle. As for me, it's better to assume an `invalid` email as `safe` or `unknown`, rather than marking `safe` emails as `invalid`. So, I propose to use `250` for checking rather than its description. Is there any subtleties with that?

**Comment by amaurymartiny** [comment]
Since I didn't know all possible `250` messages, I went the safe way and only added the ones I knew about. but maybe you're right, 250 on this command should be okay.

Would you like to create a PR?
